import { ExpanderWithHeightTransition } from "components/ExpanderWithHeightTransition";
import {
  DeleteIconButton,
  MoveIconButton,
  CollapseIconButton,
} from "components/ResumeForm/Form/IconButton";
import { AIPanel } from "components/AIPanel";
import { useAppDispatch, useAppSelector } from "lib/redux/hooks";
import {
  changeFormHeading,
  changeFormOrder,
  changeShowForm,
  selectHeadingByForm,
  selectIsFirstForm,
  selectIsLastForm,
  selectShowByForm,
  selectThemeColor,
  ShowForm,
} from "lib/redux/settingsSlice";
import {
  BuildingOfficeIcon,
  AcademicCapIcon,
  LightBulbIcon,
  WrenchIcon,
  PlusSmallIcon,
} from "@heroicons/react/24/outline";
import {
  addSectionInForm,
  deleteSectionInFormByIdx,
  moveSectionInForm,
} from "lib/redux/resumeSlice";
import { useState } from "react";

/**
 * BaseForm is the bare bone form, i.e. just the outline with no title and no control buttons.
 * ProfileForm uses this to compose its outline.
 */
export const BaseForm = ({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) => (
  <section
    className={`flex w-full flex-col gap-3 bg-white border ${className}`}
    style={{
      borderColor: "var(--border)",
      borderRadius: "var(--radius-lg)",
      boxShadow: "var(--shadow-card)",
      padding: "16px",
      marginBottom: "12px",
    }}
  >
    {children}
  </section>
);

const FORM_TO_ICON: { [section in ShowForm]: typeof BuildingOfficeIcon } = {
  workExperiences: BuildingOfficeIcon,
  educations: AcademicCapIcon,
  projects: LightBulbIcon,
  skills: WrenchIcon,
  custom: WrenchIcon,
};

export const Form = ({
  form,
  addButtonText,
  children,
}: {
  form: ShowForm;
  addButtonText?: string;
  children: React.ReactNode;
}) => {
  const showForm = useAppSelector(selectShowByForm(form));
  const heading = useAppSelector(selectHeadingByForm(form));

  const dispatch = useAppDispatch();
  const setShowForm = (showForm: boolean) => {
    dispatch(changeShowForm({ field: form, value: showForm }));
  };
  const setHeading = (heading: string) => {
    dispatch(changeFormHeading({ field: form, value: heading }));
  };

  const isFirstForm = useAppSelector(selectIsFirstForm(form));
  const isLastForm = useAppSelector(selectIsLastForm(form));
  const themeColor = useAppSelector(selectThemeColor) || "#5E6AD2";

  const handleMoveClick = (type: "up" | "down") => {
    dispatch(changeFormOrder({ form, type }));
  };

  const [aiPanelOpen, setAiPanelOpen] = useState(false);
  const [streamingText, setStreamingText] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleAIOpen = () => {
    setAiPanelOpen(true);
    setIsLoading(true);
    setTimeout(() => {
      setStreamingText("This is a sample AI-enhanced description. In production, this would be generated by an AI model based on your input.");
      setIsLoading(false);
    }, 1500);
  };

  const handleAccept = (text: string) => {
    setAiPanelOpen(false);
    setStreamingText("");
  };

  const handleRegenerate = () => {
    setIsLoading(true);
    setStreamingText("");
    setTimeout(() => {
      setStreamingText("Here is an alternative enhanced version of your description with improved wording and formatting.");
      setIsLoading(false);
    }, 1500);
  };

  const Icon = FORM_TO_ICON[form];

  return (
    <BaseForm
      className={`relative transition-opacity duration-200 ${
        showForm ? "pb-4" : "pb-2 opacity-60"
      }`}
    >
      <div
        className="flex items-center justify-between gap-2"
        onClick={() => setShowForm(!showForm)}
      >
        <div className="flex grow cursor-pointer items-center gap-2 min-w-0">
          <Icon className="h-5 w-5 shrink-0" style={{ color: "var(--muted)" }} aria-hidden="true" />
          <input
            type="text"
            className="block w-full cursor-pointer border-b border-transparent text-base font-semibold outline-none"
            style={{ color: "var(--fg)" }}
            value={heading}
            onChange={(e) => setHeading(e.target.value)}
          />
        </div>
        <div className="flex items-center gap-1 shrink-0" onClick={(e) => e.stopPropagation()}>
          {!isFirstForm && (
            <MoveIconButton type="up" onClick={handleMoveClick} />
          )}
          {!isLastForm && (
            <MoveIconButton type="down" onClick={handleMoveClick} />
          )}
          <CollapseIconButton expanded={showForm} setExpanded={setShowForm} />
        </div>
      </div>
      <ExpanderWithHeightTransition expanded={showForm}>
        {children}
      </ExpanderWithHeightTransition>
      {showForm && addButtonText && (
        <div className="flex justify-center">
          <button
            type="button"
            onClick={() => {
              dispatch(addSectionInForm({ form }));
            }}
            className="w-full py-2 text-sm font-medium rounded-md transition-colors"
            style={{
              border: "1.5px dashed var(--border)",
              color: "var(--muted)",
            }}
          >
            <PlusSmallIcon
              className="-ml-0.5 mr-1.5 h-4 w-4 inline"
              aria-hidden="true"
            />
            {addButtonText}
          </button>
        </div>
      )}
      <AIPanel
        isOpen={aiPanelOpen}
        onClose={() => setAiPanelOpen(false)}
        onAccept={handleAccept}
        onRegenerate={handleRegenerate}
        streamingText={streamingText}
        isLoading={isLoading}
      />
    </BaseForm>
  );
};

export const FormSection = ({
  form,
  idx,
  showMoveUp,
  showMoveDown,
  showDelete,
  deleteButtonTooltipText,
  onDelete,
  children,
}: {
  form: ShowForm;
  idx: number;
  showMoveUp: boolean;
  showMoveDown: boolean;
  showDelete: boolean;
  deleteButtonTooltipText: string;
  onDelete?: () => void;
  children: React.ReactNode;
}) => {
  const dispatch = useAppDispatch();
  const handleDeleteClick = () => {
    if (onDelete) {
      onDelete();
    } else {
      dispatch(deleteSectionInFormByIdx({ form, idx }));
    }
  };
  const handleMoveClick = (direction: "up" | "down") => {
    dispatch(moveSectionInForm({ form, direction, idx }));
  };

  return (
    <div
      className="relative flex flex-col gap-3 rounded-lg p-4"
      style={{
        backgroundColor: "var(--bg)",
        border: "1px solid var(--border)",
      }}
    >
      {children}
      <div className="absolute right-2 top-2 flex gap-0.5">
        <div
          className={`transition-all duration-300 ${
            showMoveUp ? "" : "invisible opacity-0"
          }`}
        >
          <MoveIconButton
            type="up"
            size="small"
            onClick={handleMoveClick}
          />
        </div>
        <div
          className={`transition-all duration-300 ${
            showMoveDown ? "" : "invisible opacity-0"
          }`}
        >
          <MoveIconButton
            type="down"
            size="small"
            onClick={handleMoveClick}
          />
        </div>
        <div
          className={`transition-all duration-300 ${
            showDelete ? "" : "invisible opacity-0"
          }`}
        >
          <DeleteIconButton
            onClick={handleDeleteClick}
            tooltipText={deleteButtonTooltipText}
          />
        </div>
      </div>
    </div>
  );
};
